### ISSUE TITLE
Replacing header formatting

### ISSUE THREAD

**Issue by sojusnik** [peter88213/zim2obsidian#1]
First of all many thanks for such a useful script!

When following your instructions to convert Zim notes to markdown through Zim's built-in export function, then header 1  is converted to

```
Header 1
=============
```

and header 2 to

```
Header 2
-------------
```

while header 3 to 5 are created with hashtags, f.i.

```
### Header 3
```

Because Obsidian also shows you the markdown code when editing text, headers with only hashtags look much cleaner than having lines, as in header 1 and 2.

Is it maybe possible, that your awesome script could also convert header 1 and 2 having hashtags instead of lines in the converted markdown files?

FYI, those are setex and atx headers, as described [here](https://daringfireball.net/projects/markdown/syntax#header).

**Comment by peter88213** [comment]
I'm glad you like it. However, after having a look at Obsidian, I decided to stick with Zim. 
So I'm afraid I can't put too much effort into developing the zim2obsidian script. But in the large Obsidian community there will surely be someone out there with Python knowledge if more features are desired. That's what open source software is all about, isn't it?

**Comment by sojusnik** [comment]
> However, after having a look at Obsidian, I decided to stick with Zim for now.

What's your reasons to return to Zim?

I'm a 10+ years heavy Zim user and find that Zim generally covers all the basic functions of an offline personal knowledge management system, but it still lacks contributions to keep up with the development of Obsidian, which is already more feature-rich than Zim, despite its young age. Although it hurts sentimentally to migrate, but in the long run Obsidian has just more potential, especially with its huge community and rich ecosystem of plugins, which gave birth to unique plugins like [Excalidraw](https://github.com/zsviczian/obsidian-excalidraw-plugin/), that reduces the gap between text and drawings (even the built-in [Canvas](https://obsidian.md/canvas) is a good start in this direction). And the mobile experience with the dedicated [Obsidian app](https://play.google.com/store/apps/details?id=md.obsidian) (which BTW should soon get a [quick capture mode](https://obsidian.md/roadmap/)) is far superior to Zim + [Markor](https://github.com/gsantner/markor/), which is often a major point in our world of interoperability.

Of course it all depends on individual preferences, but IMHO for the general user Obsidian should do it in the long run.

**Comment by peter88213** [comment]
> What's your reasons to return to Zim?

Zim (I'm still using version 0.69.1) just does the job for me, that's all. 

Obsidian, with all its possibilities to play and tinker with, is indeed tempting, but at the moment I just can't afford the time to explore its features, let alone get into plugin programming.

As for the Obsidian community, I have found the request for a Zim converter in various places, however no one else seems to have picked up on it in all these years. Strange, isn't it? Anyway, Obsitian is cool, so have a lot of fun with it!

**Comment by sojusnik** [comment]
> Obsidian, with all its possibilities to play and tinker with, is indeed tempting, but at the moment I just can't afford the time to explore its features, let alone get into plugin programming.

Was in the same situation, but decided to finally put some time aside to make the jump. The only thing that stops me from using Obsidian fully is the migration from Zim. At the moment, there seems to be no easy and automated solution. Your script is one of the most promising ones. Another one that I've found is [this](https://github.com/pschwede/zim2md) one. But it also has some issues. Let's see if the developer is interested in fixing them.

Let me know if you are interested in improving this script, because I've already found several issues. Maybe combining your script and the one from above (also written in python) would be the solution.

**Comment by peter88213** [comment]
Well, it looks like pschwede's script is to be applied directly to the zim notebook, whereas my script relies on the zim Markdown exporter to convert everything to a commonly understood Markdown format. 

Note that I didn't touch the markup created by the zim exporter at first. But with converting the header style, a line-by-line processing routine is introduced that can be extended for further conversions. Once you understand the method, this could be a beginner-level Python exercise. Maybe you'd like to pick up the spirit of the open source movement, and get involved with the code yourself?

This is the pattern in zim2obsidian.py:

```
        # Replace Setext-style headers with Atx-style headers; convert rulers.
        newLines = []
        previousLine = None
        for  line in lines:
            if line.startswith('=') and line.count('=') == len(line):
                print(f'Converting 1st level heading "{previousLine}" ...')
                previousLine = f'# {previousLine}'
            elif line.startswith('-') and line.count('-') == len(line):
                print(f'Converting 2nd level heading "{previousLine}" ...')
                previousLine = f'## {previousLine}'
            elif line.startswith('*') and line.count('*') == len(line):
                print('Converting horizontal ruler ...')
                if previousLine is not None:
                    newLines.append(previousLine)
                previousLine = '---'

            # Just add another conversion here:

            elif (line contains other markup to convert):
                if previousLine is not None:
                    newLines.append(previousLine)

                (replace old markup with new markup in previousLine) 
            
            #######

            else:
                if previousLine is not None:
                    newLines.append(previousLine)
                previousLine = line
```
