### ISSUE TITLE
Text indentations aren't converted properly

### ISSUE THREAD

**Issue by sojusnik** [peter88213/zim2obsidian#11]
**Application/script**
- Version: v0.6.6

**Describe the bug**
Indentations of text by using the tab key aren't converted properly after Zim's markdown export, although indentations with checkboxes do work, see examples below.

**To Reproduce**
1. Copy the following to your zim file:
```
indentations by using tab aren't converted properly after Zim's markdown conversion
	indentation of normal text by using one tab
		indentation of normal text by using two tabs
			indentation of normal text by using three tabs

[ ] indentations with checkboxes work though
	[ ] indented checkbox by using one tab
		[ ] indented checkbox by using two tabs

[ ] indentations following a checkbox aren't converted properly either
	indentation of normal text by using one tab
		indentation of normal text by using two tabs
			indentation of normal text by using three tabs
```
2. Convert this page via Zim's export function to markdown
3. Open in Obsidian

**Expected behavior**
Text should be indented, as it is displayed in Zim.

**Execution environment (please complete the following information):**
- Python Version: Python 3.11.2
- OS: Ubuntu 23.04

**Comment by sojusnik** [comment]
Updated this issue

**Comment by peter88213** [comment]
When pressing the "Tab" key with Zim, a tab character (U+0009) is inserted.
Be aware that tabs, like multiple blanks, aren't specified in Markdown. It's advised to use  `&nbsp;` or `&emsp;` instead when typing Markdown formatted text with a text editor. 

However, the tab character gets lost upon Zim's Markdown export see [open issues here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/zim/formats/markdown.py). This is why *zim2obsidian* cannot keep it using the method mentioned above.

**Comment by peter88213** [comment]
A solution is now proposed here:
https://github.com/peter88213/zim2obsidian/issues/13#issuecomment-1650446635
