### ISSUE TITLE
Highlighted text isn't converted

### ISSUE THREAD

**Issue by sojusnik** [peter88213/zim2obsidian#12]
**Application/script**
- Version: v0.6.6

**Describe the bug**
Highlighted text `__like this__` (in Zim) should be converted as `==highlighted text==` in Obsidian. Currently, this type of text formatting isn't converted.

**Execution environment (please complete the following information):**
- Python Version: Python 3.11.2
- OS: Ubuntu 23.04

**Comment by peter88213** [comment]
This can be easily done with a simple regex replacement, like 
`line = re.sub('__(.+)__', '==\\1==', line)`

**Comment by peter88213** [comment]
## Specification

### Original data:

```
blabla __highlighted__ blabla __highlighted__.
```

### Processed data:

```
blabla ==highlighted== blabla ==highlighted==.
```
