### ISSUE TITLE
Tags aren't converted

### ISSUE THREAD

**Issue by sojusnik** [peter88213/zim2obsidian#14]
**Application/script**
- Version: v0.8.1

**Describe the bug**
Currently, tags aren't converted.

**Expected behavior**
Zim tags `@tags` should be converted to Obsidian `#tags`.
Several tags in a row like `@tag1` `@tag2` `@tag3` should also be converted with a space between them to `#tag1` `#tag2` `#tag3`.

**Execution environment (please complete the following information):**
- Python Version: 3.11.2
- OS: Ubuntu 23.04

**Comment by peter88213** [comment]
original data:

```
@Tag1 @Tag2 @Tag3
```

Note: In this example, there aren't spaces at the beginning and the end of the line.

processed data:

```
 #Tag1 Tag2 Tag3
```

Note: A space must be inserted at the beginning of the line Do not convert it to a heading.

**Comment by sojusnik** [comment]
> For ease of implementation and faster execution, a space is always added to the beginning of the Obsidian tag.

May I ask why the space before an Obsidian tag is needed?

In Obsidian headers always have a space between `#` and the header name, while tags don't, regardless if a tag is at the beginning of a new line or after a word, e.g:
```
# header 1

#tagatthebeginning and that's a normal text #tagattheend 
	#tagaftertab
 #tagafterspace
```
Which looks like:
![image](https://github.com/peter88213/zim2obsidian/assets/1245718/1f296921-a985-4d83-9559-9b219a02abc5)

**Comment by peter88213** [comment]
If this is so, you can try out a patch without the space. 

Have a look at line 199:
```
                    line = re.sub('@(\S+?)', ' #\\1', line)
```
and change the code to
```
                    line = re.sub('@(\S+?)', '#\\1', line)
``` 
(delete the space before `#\\1`)

If the conversion result is satisfying for you, let me know, and I will make a new release.

**Comment by sojusnik** [comment]
> If the conversion result is satisfying for you, let me know, and I will make a new release.

Working perfectly now! Thank you 🙏🏼

**Comment by peter88213** [comment]
Well then, this will be my last work on *zim2obsidian* for now. Thank you for your feedback and for your input. 

Here's the updated spec:

## Specification
### Original data:

```
@Tag1 @Tag2 @Tag3
@ @
@
@Tag4@Tag5
@@Tag6
```

Note: 
- In this example, there aren't spaces at the beginning and the end of the line.

### Processed data:

```
#Tag1 #Tag2 #Tag3
@ @
@
#Tag4#Tag5
#@Tag6
```

### Processing invalid input:
- Tag5 and Tag6 are not valid Zim tags. However, they are created as Obsidian tags with v0.10.3.
